### PR TITLE
Attemping to add in unicast sending support

### PR DESCRIPTION
**Pull request by twotabsofacid**
Hello – I used your library to implement sACN over unicast and had to make some tweaks to make it work, so I'm putting those here in case you feel like merging them in. I don't know much about UDP, or unicast vs multicast generally, but on the network I'm currently on this has been working to communicate with a device via unicast. I _think_ this might be a weird use-case, where multicast isn't set up at all on the network I'm on so I was getting a `dgram` error when trying to use the `sender` to send data:

```
dgram.js:813
    throw errnoException(err, 'setMulticastInterface');
```

But, truthfully I have no clue. All I can confirm is that this does in fact send information via unicast to a device on my local network. Let me know if you want me to make any changes or if I'm doing something stupid 🤪 

I also added some code to send a sync packet following the data (it's almost the exact same, but with a sync header `0x00000008` instead of a data header `0x00000004` in the packet)

### CODE REVIEW

**Comment by sparks-alec** [comment]
This rules. Thank you! I'll double-check everything is a-ok this weekend and merge.

**Comment by twotabsofacid** [comment]
Rad! On the [master branch](https://github.com/twotabsofacid/stagehack-sACN/tree/master) of the fork I separated out the sender from the sync, which I think might be the better way to go about this (requiring a `sync` packet I _think_ isn't really standard, but was required for what I was doing). Going to clean up before this weekend and open a PR for that one unless you prefer having the sync packet send by default.

**Comment by twotabsofacid** [comment]
[this pr is the better one to look at](https://github.com/stagehacks/stagehack-sACN/pull/3), but leaving this one up for comparison or whatever 👍

**Comment by twotabsofacid** [comment]
Ok @sparks-alec think this should be good to go: just includes unicast support, got rid of all mentions of sync, and did some linting to go with 2 spaces across the board. I'll open a separate PR for Sync packet support once i figure out how to add in some tests that don't yield weird results 😵

**Review by sparks-alec — APPROVED** [review]

**Pull request merged**
